export const ActionTypes = {
  SET_POKEMON: "GET_POKEMON",
  SET_POKEMON_BY_GENDER: "SET_POKEMON_BY_GENDER",
  SELECTED_POKEMON: "SELECTED_POKEMON",
  SELECTED_POKEMON_BY_GENDER: "SELECTED_POKEMON_BY_GENDER",
  SELECTED_OPTION: "SELECTED_OPTION",
};
